//
//  DefaultWordsList.swift
//  WordsLearning
//
//  Created by Roman Kuzin on 15.08.2022.
//

struct DefaultWordsList {
	
	static let wordsList = [
        Word(foreign: "אני", native: ["я"], transcription: "аньи", partOfSpeech: .other),
        Word(foreign: "את", native: ["ты"], transcription: "ат", partOfSpeech: .other, nToFRemark: "ж.р"),
        Word(foreign: "אתה", native: ["ты"], transcription: "ата", partOfSpeech: .other, nToFRemark: "м.р"),
        Word(foreign: "היא", native: ["она"], transcription: "hи", partOfSpeech: .other),
        Word(foreign: "אימא", native: ["мама"], transcription: "има"),
        Word(foreign: "יין", native: ["вино"], transcription: "яйн"),
        Word(foreign: "מים", native: ["вода"], transcription: "майм"),
        Word(foreign: "ים", native: ["море"], transcription: "ям"),
        Word(foreign: "מתנה", native: ["подарок"], transcription: "матана!", nToFRemark: "ж.р"),
        Word(foreign: "מי", native: ["кто"], transcription: "ми?", partOfSpeech: .questionWord, fToNRemark: "?", nToFRemark: "?"),
        Word(foreign: "מה", native: ["что"], transcription: "ма?", partOfSpeech: .questionWord, fToNRemark: "?", nToFRemark: "?"),
        Word(foreign: "הוא", native: ["он"], transcription: "hу", partOfSpeech: .other),
        Word(foreign: "איש", native: ["человек(мужчина)"], transcription: "ищ/анащим"),
        Word(foreign: "אישה", native: ["женщина", "жена"], transcription: "ища"),
        Word(foreign: "ילד", native: ["ребенок"], transcription: "йелед"),
        Word(foreign: "תלמיד", native: ["ученик"], transcription: "тальмид/тальмиди!м"),
        Word(foreign: "שמש", native: ["солнце"], transcription: "ще!мещ"),
        Word(foreign: "דגל", native: ["флаг"], transcription: "дэ!гэль/дгали!м"),
        Word(foreign: "שיר", native: ["песня"], transcription: "щир/щирим"),
        Word(foreign: "הר", native: ["гора"], transcription: "хар/хари!м"),
        Word(foreign: "גלידה", native: ["мороженое"], transcription: "глида!"),
        Word(foreign: "מאין", native: ["откуда"], transcription: "мэ-а!йн", partOfSpeech: .questionWord, fToNRemark: "?", nToFRemark: "?"),
        Word(foreign: "שם", native: ["там"], transcription: "щам", partOfSpeech: .other),
		Word(foreign: "כותב", native: ["пишет"], transcription: "котэ!в", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "כותבת", native: ["пишет"], transcription: "котэ!вэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "לכתוב", native: ["писать"], transcription: "лихтов", partOfSpeech: .verb),
		Word(foreign: "יודע", native: ["знает", "умеет"], transcription: "ёде!а", partOfSpeech: .verb, nToFRemark: "что-то, м.р"),
		Word(foreign: "יודעת", native: ["знает", "умеет"], transcription: "ёдаат", partOfSpeech: .verb, nToFRemark: "что-то, ж.р"),
		Word(foreign: "לדעת", native: ["знать", "уметь"], transcription: "ладаат", partOfSpeech: .verb),
		Word(foreign: "רוצא", native: ["хочет"], transcription: "роцэ!", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "אוהב", native: ["любит"], transcription: "оhэв", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "אוהבת", native: ["любит"], transcription: "оhэвэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "לאהוב", native: ["любить"], transcription: "леэhов", partOfSpeech: .verb),
		Word(foreign: "הולך", native: ["идет", "ходит"], transcription: "hоле!х", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "הולכת", native: ["идет", "ходит"], transcription: "hолехэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "ללכת", native: ["идти", "ходить"], transcription: "льалехэт", partOfSpeech: .verb),
		Word(foreign: "בא", native: ["приходит", "входит"], transcription: "ба", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "נוסע", native: ["едет", "ездит"], transcription: "носэ!а", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "נוסעת", native: ["едет", "ездит"], transcription: "носаат", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "לנסוע", native: ["ехать", "ездить"], transcription: "линсоа", partOfSpeech: .verb),
		Word(foreign: "מדבר", native: ["разговаривает", "говорит"], transcription: "медабэр/медабэрэт", partOfSpeech: .verb),
		Word(foreign: "קורא", native: ["читает"], transcription: "корэ!/корэт", partOfSpeech: .verb),
		Word(foreign: "לקרוא", native: ["читать"], transcription: "ликро", partOfSpeech: .verb),
		Word(foreign: "לומד", native: ["изучает", "учится"], transcription: "льомэ!д", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "שומע", native: ["слушает", "слышет"], transcription: "шомеа", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "שומעת", native: ["слушает", "слышет"], transcription: "шомаат", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "לשמוע", native: ["слушать", "слышать"], transcription: "лишмоа", partOfSpeech: .verb),
		Word(foreign: "שר", native: ["поет"], transcription: "шир", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "שרה", native: ["поет"], transcription: "шира", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "לשיר", native: ["петь"], transcription: "лашир", partOfSpeech: .verb),
		Word(foreign: "עושה", native: ["делает"], transcription: "осэ!/оса", partOfSpeech: .verb),
		Word(foreign: "לעשות", native: ["делать"], transcription: "лаасот", partOfSpeech: .verb),
		Word(foreign: "שותה", native: ["пьет"], transcription: "шотэ!|шота", partOfSpeech: .verb),
		Word(foreign: "לשתות", native: ["пить"], transcription: "лиштот", partOfSpeech: .verb),
		Word(foreign: "גר", native: ["проживает"], transcription: "гар", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "גרה", native: ["проживает"], transcription: "гара!", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "לגור", native: ["проживать"], transcription: "лагур", partOfSpeech: .verb, nToFRemark: "где-то"),
		Word(foreign: "עובד", native: ["работает"], transcription: "овэ!д", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "עובדת", native: ["работает"], transcription: "овэдэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "לעבוד", native: ["работать"], transcription: "ляавод", partOfSpeech: .verb),

		// MARK: - Some other
        
		Word(foreign: "מבין", native: ["понимает"], transcription: "мэви!н", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "אומר", native: ["говорит"], transcription: "омэр/омэрэт"),
		Word(foreign: "לומר", native: ["сказать", "говорить"], transcription: "льомар"),
		Word(foreign: "מצטער", native: ["сожалеет"], transcription: "мицтаэ!р", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "מצטערת", native: ["сожалеет"], transcription: "мицтаэрэт", partOfSpeech: .verb, nToFRemark: "ж.р"),

		Word(foreign: "סרט", native: ["фильм", "кино"], transcription: "сэ!рэт"),
		Word(foreign: "ספרייה", native: ["библиотека"], transcription: "сифрия!"),
		Word(foreign: "אולי", native: ["может быть"], transcription: "уляй", partOfSpeech: .other),
		Word(foreign: "נכון", native: ["верно", "правильно"], transcription: "нахо!н", partOfSpeech: .other),
		Word(foreign: "חנות", native: ["магазин"], transcription: "хану!т"),
		Word(foreign: "חבר", native: ["друг", "бойфренд"], transcription: "хавэ!р"),
		Word(foreign: "חברה", native: ["подруга", "герлфренд"], transcription: "хавера!"),
		Word(foreign: "מספר", native: ["номер"], transcription: "миспа!р"),
		Word(foreign: "טלפון נייד", native: ["мобильный телефон"], transcription: "тэлефон ная!д"),

		// MARK: - урок 2.1
        
		Word(foreign: "גדול", native: ["большой"], transcription: "гадо!ль", partOfSpeech: .adjective),
		Word(foreign: "גדולה", native: ["большая"], transcription: "гдольа!", partOfSpeech: .adjective),
		Word(foreign: "קטן", native: ["маленький"], transcription: "ката!н", partOfSpeech: .adjective),
		Word(foreign: "קטנה", native: ["маленькая"], transcription: "ктана!", partOfSpeech: .adjective),
		Word(foreign: "חדש", native: ["новый"], transcription: "хада!ш", partOfSpeech: .adjective),
		Word(foreign: "חדשה", native: ["новая"], transcription: "хадаша!", partOfSpeech: .adjective),
		Word(foreign: "עתיק", native: ["древний(м.р)"], transcription: "ати!к", partOfSpeech: .adjective),
		Word(foreign: "עתיקה", native: ["древняя"], transcription: "атика!", partOfSpeech: .adjective),
		Word(foreign: "מודרני", native: ["современный(м.р)"], transcription: "модэ!рни", partOfSpeech: .adjective),
		Word(foreign: "מודרנית", native: ["современная"], transcription: "модэ!рнит", partOfSpeech: .adjective),
		Word(foreign: "מיוחד", native: ["особенный"], transcription: "мэюха!д", partOfSpeech: .adjective),
		Word(foreign: "מיוחדת", native: ["особенная"], transcription: "мэюхэ!дет", partOfSpeech: .adjective),
		Word(foreign: "יפה", native: ["красивый", "красивая"], transcription: "ёфэ!/ёфа!", partOfSpeech: .adjective),
		Word(foreign: "רומי", native: ["римский(м.р)"], transcription: "ро!ми", partOfSpeech: .adjective),
		Word(foreign: "רומית", native: ["римская"], transcription: "ро!мит", partOfSpeech: .adjective),
		Word(foreign: "רחוב", native: ["улица"], transcription: "рэхо!в"),
		Word(foreign: "רחובות", native: ["улицы"], transcription: "рэхово!т"),
		Word(foreign: "ארמון", native: ["замок", "дворец"], transcription: "армо!н"),
		Word(foreign: "ארמונות", native: ["замки", "дворцы"], transcription: "армоно!т"),
		Word(foreign: "ציור", native: ["рисунок"], transcription: "циу!р|циури!м"),
		Word(foreign: "קיסר", native: ["император", "цезарь"], transcription: "кейса!р"),
		Word(foreign: "עלשם", native: ["имени", "памяти"], transcription: "альше!м", partOfSpeech: .other),
		Word(foreign: "לפעמים", native: ["иногда"], transcription: "лифами!м", partOfSpeech: .other),
		Word(foreign: "כמו", native: ["как"], transcription: "кмо!", partOfSpeech: .pretext, nToFRemark: "предлог"),
		Word(foreign: "איזה", native: ["какой"], transcription: "эйзэ!", partOfSpeech: .questionWord, nToFRemark: "?"),
		Word(foreign: "איזו", native: ["какая"], transcription: "эзо!", partOfSpeech: .questionWord, nToFRemark: "?"),
		Word(foreign: "אילו", native: ["какие"], transcription: "э!льо", partOfSpeech: .questionWord, nToFRemark: "?"),
        
		// MARK: - урок 2.2
        
		Word(foreign: "דירה", native: ["квартира"], transcription: "дира!/диро!т"),
		Word(foreign: "חדר", native: ["комната"], transcription: "хэ!дэр/хадари!м"),
		Word(foreign: "סלון", native: ["салон(зал)"], transcription: "сальо!н/сальони!м"),
		Word(foreign: "מטבח", native: ["кухня"], transcription: "митба!х/митбахим"),
		Word(foreign: "מקלחת", native: ["душ"], transcription: "микля!хат/микляхо!т"),
		Word(foreign: "גינה", native: ["палисадник"], transcription: "гина!/гино!т"),
		Word(foreign: "עץ", native: ["дерево"], transcription: "эц/эци!м"),
		Word(foreign: "שולחן", native: ["стол"], transcription: "шульха!н/шульхано!т"),
		Word(foreign: "חנוכייה", native: ["ханукия"], transcription: "ханукия!/ханукио!т"),
		Word(foreign: "ישן", native: ["старый"], transcription: "яша!н|яшана!", partOfSpeech: .adjective, nToFRemark: "о вещах"),
		Word(foreign: "קלסי", native: ["класический"], transcription: "кльа!си", partOfSpeech: .adjective),
		Word(foreign: "קלסית", native: ["класическая"], transcription: "кльаси!т", partOfSpeech: .adjective),
		Word(foreign: "מצוין", native: ["отличный", "отлично"], transcription: "мэцуя!н/мэцуе!нет", partOfSpeech: .adjective),
		Word(foreign: "טוב", native: ["хороший", "хорошо"], transcription: "тов(м.р)/това(ж.р)", partOfSpeech: .adjective),
		Word(foreign: "נחמד", native: ["милый", "хороший"], transcription: "нэхма!д|нэхмада!", partOfSpeech: .adjective),
		Word(foreign: "בטה", native: ["конечно", "несомненно", "наверняка"], transcription: "бэ!тах", partOfSpeech: .other),
		Word(foreign: "למשל", native: ["например"], transcription: "лемаша!ль", partOfSpeech: .other),
		Word(foreign: "בקשר ל", native: ["в отношении(кого-то, чего-то)"], transcription: "бэкэ!шер ле", partOfSpeech: .other),
		Word(foreign: "בית", native: ["дом"], transcription: "байт/бати!м"),
		Word(foreign: "כמה", native: ["несколько"], transcription: "кама!", partOfSpeech: .other),
		// MARK: - урок 3.1

		// MARK: - урок 3.2
        
		Word(foreign: "רחיט", native: ["мебель(ед.ч, предмет)"], transcription: "рахи!т"),
		Word(foreign: "רחיטים", native: ["мебель(мн.ч, предметы)"], transcription: "рахити!м"),
		Word(foreign: "כיסא", native: ["стул"], transcription: "кисэ!/кисо!т"),
		Word(foreign: "מיטה", native: ["кровать"], transcription: "мита!/мито!т"),
		Word(foreign: "שטיח", native: ["ковер"], transcription: "шати!ах/штихи!м"),
		Word(foreign: "אוהל", native: ["палатка", "шатер"], transcription: "оhэ!ль/оhали!м"),
		Word(foreign: "מקום", native: ["место"], transcription: "мако!м/мэкомо!т"),
		Word(foreign: "גבר", native: ["мужчина", "мужик"], transcription: "гэ!вер/гвари!м"),
		Word(foreign: "בית כנסת", native: ["синагога"], transcription: "бэ!йт кне!сет"),
		Word(foreign: "בתי בנסת", native: ["синагоги"], transcription: "батэ!й кне!сет"),
		Word(foreign: "דקה", native: ["минута"], transcription: "дака!/дако!т"),
		Word(foreign: "ישראלי", native: ["израильский" ,"израильтянин"], transcription: "исрэили!"),
		Word(foreign: "ישראלים", native: ["израильская" ,"израильтянка"], transcription: "исрэили!м"),
		Word(foreign: "בדואי", native: ["бедуинский", "бедуин"], transcription: "бэ!дуи"),
		Word(foreign: "בדואים", native: ["бедуинская", "бедуинка"], transcription: "бэдуи!м"),
		Word(foreign: "חיום", native: ["сегодня(м.р)"], transcription: "хайом"),
		Word(foreign: "אחר", native: ["другой"], transcription: "ахэ!р", partOfSpeech: .adjective),
		Word(foreign: "אחרת", native: ["другая"], transcription: "ахэ!рэт", partOfSpeech: .adjective),
		Word(foreign: "אוכל", native: ["ест", "кушает"], transcription: "охэ!ль", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "אוכלת", native: ["ест", "кушает"], transcription: "охэ!лэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "יושב", native: ["сидит"], transcription: "йоше!в/йоше!вэт", nToFRemark: "м.р"),
		Word(foreign: "מטייל", native: ["гуляет"], transcription: "метайе!ль/метайе!льэт", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "רואה", native: ["видит(м.р|ж.р)"], transcription: "ро-э! | ро-а!", partOfSpeech: .verb),
		Word(foreign: "לראות", native: ["видеть"], transcription: "лирот", partOfSpeech: .verb),

		// MARK: - lesson 5.1
		Word(foreign: "בגד", native: ["одежда"], transcription: "бэ!гед"),
		Word(foreign: "בגדים", native: ["одежды"], transcription: "бгади!м"),
		Word(foreign: "ג׳ינס", native: ["джинсы(ед.ч)"], transcription: "джи!нс"),
		Word(foreign: "ג׳ינסים", native: ["джинсы(мн.ч)"], transcription: "джи!нсим"),
		Word(foreign: "זמן", native: ["время"], transcription: "зман"),
		Word(foreign: "זמנים", native: ["времена"], transcription: "зманим"),
		Word(foreign: "מחר", native: ["завтра"], transcription: "маха!р"),
		Word(foreign: "רץ", native: ["бежит"], transcription: "рац", partOfSpeech: .verb, nToFRemark: "м.р"),
        Word(foreign: "רצה", native: ["бежит"], transcription: "раца!", partOfSpeech: .verb, nToFRemark: "ж.р"),
        Word(foreign: "לרוץ", native: ["бегать", "бежать"], transcription: "ларуц", partOfSpeech: .verb),
        Word(foreign: "לובש", native: ["надевает"], transcription: "льовэ!ш/льовэ!шет", nToFRemark: "м.р"),
        Word(foreign: "שואל", native: ["спрашивает"], transcription: "що-эль/що-элет", nToFRemark: "м.р"),
        Word(foreign: "חושב", native: ["думает"], transcription: "хощев", partOfSpeech: .verb, nToFRemark: "м.р"),
        Word(foreign: "חושבת", native: ["думает"], transcription: "хощэвэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
        Word(foreign: "לחשוב", native: ["думать"], transcription: "лахшов/лахашов", partOfSpeech: .verb),

        // MARK: - lesson 5.2
        
        Word(foreign: "בעל", native: ["муж"], transcription: "баа!ль/беали!м"),
        Word(foreign: "יהודי", native: ["еврей"], transcription: "ехуди!"),
        Word(foreign: "יהודייה", native: ["еврейка"], transcription: "ехудия"),
        Word(foreign: "רב", native: ["равин"], transcription: "рав/равани!м"),
        Word(foreign: "שם", native: ["имя"], transcription: "щем/щемо!т"),
        Word(foreign: "שמי", native: ["моё имя"], transcription: "щми"),
        Word(foreign: "מישהו", native: ["кто-нибудь", "кто нибудь", "ктонибудь"], transcription: "мищэху!", partOfSpeech: .other),
        Word(foreign: "מי ש", native: ["тот, кто", "тот кто"], transcription: "ми шэ", partOfSpeech: .other),
        Word(foreign: "מה שמך", native: ["как тебя зовут(?)", "как зовут(?)"], transcription: "ма шимха(к мужчине)\nма шмех(к женщине)", partOfSpeech: .other),
        Word(foreign: "לאט", native: ["медленно"], transcription: "леа!т", partOfSpeech: .adjective),
        Word(foreign: "מהר", native: ["быстро"], transcription: "маhэ!р", partOfSpeech: .adjective),
        Word(foreign: "קשה", native: ["тяжело"], transcription: "кашэ!", partOfSpeech: .adjective),
        Word(foreign: "שאלה", native: ["вопрос"], transcription: "щэ-ельа/ще-ельот"),
        Word(foreign: "מאה", native: ["сто", "сотня", "век"], transcription: "мэ-а(м.р)/мэ-от(ж.р)", partOfSpeech: .other),
        Word(foreign: "קורס", native: ["курс"], transcription: "курс/курси!м"),
        Word(foreign: "בשקט", native: ["тихо"], transcription: "бэше!кет", nToFRemark: "досл.:в тишине"),

        // lesson 6.2
        Word(foreign: "דרך", native: ["дорога", "путь"], transcription: "дэрэх/драхим"),
        Word(foreign: "מלון", native: ["отель"], transcription: "мальон/мэльонот"),
        Word(foreign: "ים המלח", native: ["мертвое море"], transcription: "ям ха мэлях"),
        Word(foreign: "מדבר", native: ["пустыня"], transcription: "мидбар"),
        Word(foreign: "שקט", native: ["тишина"], transcription: "шекет"),
        Word(foreign: "הכול", native: ["все", "всё"], transcription: "хаколь", partOfSpeech: .other),
        Word(foreign: "חם", native: ["горячий"], transcription: "хам/хамим", partOfSpeech: .adjective),
        Word(foreign: "עיינות", native: ["источники", "родники"], transcription: "аянот"),
        Word(foreign: "תייר", native: ["турист"], transcription: "тайар/тайарим"),
        Word(foreign: "מחוייל", native: ["изза границы","из-за границы"], transcription: "михуль", partOfSpeech: .other),
        Word(foreign: "ארץ", native: ["страна", "земля"], transcription: "э!рэц"),
        Word(foreign: "חולה", native: ["больной", "больная"], transcription: "хольэ/хольэ", partOfSpeech: .adjective),
        Word(foreign: "אמצע", native: ["середина", "половина"], transcription: "э!мца"),
        Word(foreign: "הם", native: ["они", "равно"], transcription: "hэм", partOfSpeech: .other),
        Word(foreign: "ועוד", native: ["плюс"], transcription: "вэод"),
        Word(foreign: "פחות", native: ["минус"], transcription: "пахот"),

        // lesson 7.2
        Word(foreign: "בעיה", native: ["проблема"], transcription: "бэ-айа/бэ-айот(ж.р)"),
        Word(foreign: "כובע", native: ["кепка", "шляпа"], transcription: "кова/коваим"),
        Word(foreign: "כובע טמבל", native: ["панама", "панамка"], transcription: "ко!ва тэмбэ!ль", nToFRemark: "досл.: глупая шляпа"),
        Word(foreign: "צבא", native: ["армия"], transcription: "цава/цва!от"),
        Word(foreign: "מלחמה", native: ["война"], transcription: "мильхама/мильхамот"),
        Word(foreign: "שנה", native: ["год"], transcription: "щана!/щаним"),
        Word(foreign: "סיפור", native: ["рассказ"], transcription: "сипур/сипурим"),
        Word(foreign: "משוגע", native: ["сумасшедший"], transcription: "мэщуга/мэщугаат", partOfSpeech: .adjective),

        // lesson 7.2_additional
        Word(foreign: "מעניין", native: ["интересно"], transcription: "меанйен", partOfSpeech: .other),
        Word(foreign: "פוגש", native: ["встречает", "знакомится"], transcription: "погэщ/погэщэт", partOfSpeech: .verb),
        Word(foreign: "לפגוש", native: ["встречать", "знакомиться"], transcription: "лифгош", partOfSpeech: .verb),
        Word(foreign: "חקלאות", native: ["сельское хозяйство"], transcription: "хакляут", partOfSpeech: .verb),
        Word(foreign: "טבע", native: ["природа"], transcription: "те!ва", partOfSpeech: .verb),
        Word(foreign: "לילה", native: ["ночь", "вечер"], transcription: "льайльа", partOfSpeech: .verb),
        Word(foreign: "אבל", native: ["но"], transcription: "аваль", partOfSpeech: .verb),
        Word(foreign: "להיות", native: ["быть", "стать", "становиться"], transcription: "лехийот", partOfSpeech: .verb),
        Word(foreign: "משפחה", native: ["семья"], transcription: "мищпаха", partOfSpeech: .verb),
        Word(foreign: "שואל", native: ["спрашивает", "просит"], transcription: "шоэль/шоэ!лет", partOfSpeech: .verb),
        Word(foreign: "לשאול", native: ["спрашивать", "просить", "спросить"], transcription: "лишоль", partOfSpeech: .verb),

        // MARK: - lesson 9.1
        
        Word(foreign: "לדבר", native: ["разговаривать"], transcription: "ледабэр", partOfSpeech: .verb),
        Word(foreign: "מקבל", native: ["получает", "принимает"], transcription: "мэкабэль", partOfSpeech: .verb, fToNRemark: "м.р"),
        Word(foreign: "לקבל", native: ["получать", "принимать"], transcription: "лекабэль", partOfSpeech: .verb),
        Word(foreign: "לטייל", native: ["гулять"], transcription: "летайель", partOfSpeech: .verb),
        Word(foreign: "מחפש", native: ["ищет"], transcription: "мехапэс", partOfSpeech: .verb, nToFRemark: "м.р"),
        Word(foreign: "לחפש", native: ["искать"], transcription: "лехапэс", partOfSpeech: .verb),
        Word(foreign: "משחק", native: ["играет"], transcription: "месахэк", partOfSpeech: .verb, nToFRemark: "м.р"),
        Word(foreign: "לשחק", native: ["играть"], transcription: "лэсахэк", partOfSpeech: .verb),
        Word(foreign: "משלם", native: ["платит", "оплачивает"], transcription: "мешалем", partOfSpeech: .verb, nToFRemark: "м.р"),
        Word(foreign: "לשלם", native: ["платить", "оплачивать"], transcription: "лешалем", partOfSpeech: .verb),
        Word(foreign: "מספר", native: ["рассказывает"], transcription: "месапэр", partOfSpeech: .verb, nToFRemark: "м.р"),
        Word(foreign: "לספר", native: ["рассказывать"], transcription: "лесапэр", partOfSpeech: .verb),
        Word(foreign: "מבקר", native: ["навещает", "посещает"], transcription: "мевакер", partOfSpeech: .verb, fToNRemark: "м.р"),
        Word(foreign: "לבקר", native: ["навещать(אֶת‎)", "посещать(בְּ‎)"], transcription: "левакер", partOfSpeech: .verb),
        Word(foreign: "לשים", native: ["класть", "ложить"], transcription: "льасим", partOfSpeech: .verb),
        Word(foreign: "שם", native: ["положил"], transcription: "сам", partOfSpeech: .verb, nToFRemark: "м.р"),
        Word(foreign: "שמה", native: ["положила"], transcription: "сама", partOfSpeech: .verb),

        // lesson 9.1_additional

        Word(foreign: "גנן", native: ["садовник"], transcription: "ганан/гананим"),
        Word(foreign: "קניון", native: ["торговый центр", "молл"], transcription: "канъйон/канъйоним"),
        Word(foreign: "מסיבה", native: ["вечеринка", "банкет"], transcription: "мсиба/мсибот"),
        Word(foreign: "פרח", native: ["цветок"], transcription: "пе!рах/прахим"),
        Word(foreign: "שוק", native: ["рынок"], transcription: "щук/щваким"),
        Word(foreign: "סוף", native: ["конец"], transcription: "соф", nToFRemark: "м.р"),
        Word(foreign: "חול", native: ["песок"], transcription: "холь/хольот"),
        Word(foreign: "סוף שבוע", native: ["уикенд", "выходные"], transcription: "сов шавуа"),
        Word(foreign: "שנה", native: ["год"], transcription: "шана/шаним"),
        Word(foreign: "עיתון", native: ["газета"], transcription: "итон/итоним"),
        Word(foreign: "כסף", native: ["деньги"], transcription: "кэсэф"),
        Word(foreign: "עבודה", native: ["работа"], transcription: "авода"),
        Word(foreign: "הרבה", native: ["много"], transcription: "hарбэ", partOfSpeech: .other),
        Word(foreign: "מתוק", native: ["сладкий"], transcription: "маток", partOfSpeech: .adjective),
        Word(foreign: "מתוקה", native: ["сладкая"], transcription: "мэтука", partOfSpeech: .adjective),
        Word(foreign: "למודיעין", native: ["для разведки", "в разведке"], transcription: "ле/бэ модиин", partOfSpeech: .other),
        Word(foreign: "בן כמה", native: ["сколько лет", "сколько тебе лет"], transcription: "бэн кама?", partOfSpeech: .questionWord, fToNRemark: "? к муж."),
        Word(foreign: "בת כמה", native: ["сколько лет", "сколько тебе лет"], transcription: "бат кама?", partOfSpeech: .questionWord, fToNRemark: "? к жен."),

		// MARK: - lesson 11.1

		Word(foreign: "שלי", native: ["мой","моё", "моя", "мое", "мои"], transcription: "шели!", partOfSpeech: .other),
		Word(foreign: "שלך", native: ["твой", "твои", "твое", "твоё"], transcription: "шельха - для м.р.\nшельах - для ж.р.", partOfSpeech: .other),
		Word(foreign: "שלו", native: ["его", "ему"], transcription: "шельо!", partOfSpeech: .other),
		Word(foreign: "שלה", native: ["ее", "ей", "её"], transcription: "шельа!", partOfSpeech: .other),
		Word(foreign: "שלנו", native: ["наш", "наше", "наши"], transcription: "шельа!ну", partOfSpeech: .other),
		Word(foreign: "שלכם", native: ["ваша", "ваши", "ваш", "ваше"], transcription: "шельахэ!м", partOfSpeech: .other, nToFRemark: "Местоимение для мн.ч. м.р"),
		Word(foreign: "שלכן", native: ["ваша", "ваши", "ваш", "ваше"], transcription: "шельахэ!н", partOfSpeech: .other, nToFRemark: "Местоимение для мн.ч. ж.р"),
		Word(foreign: "שלהם", native: ["их"], transcription: "шельаhэ!м", partOfSpeech: .other, nToFRemark: "Местоимение для мн.ч. м.р"),
		Word(foreign: "שלהן", native: ["их"], transcription: "шельаhэ!н", partOfSpeech: .other, nToFRemark: "Местоимение для мн.ч. ж.р"),
		Word(foreign: "כלב", native: ["собака"], transcription: "келев/кльави!м", partOfSpeech: .noun),
		Word(foreign: "חתול", native: ["кот"], transcription: "хату!ль/хатули!м", partOfSpeech: .noun, nToFRemark: "м.р."),
		Word(foreign: "חתולה", native: ["кошка"], transcription: "хатульа!/хатульо!т", partOfSpeech: .noun, nToFRemark: "ж.р."),
		Word(foreign: "לתת", native: ["давать", "дать"], transcription: "льатэ!т", partOfSpeech: .verb),
		Word(foreign: "נותן", native: ["дает", "даёт"], transcription: "нотэ!н/нотэ!нэт\nнот-ни!м/нот-но!т", partOfSpeech: .verb),
		Word(foreign: "לעמוד", native: ["стоять"], transcription: "льа-а!мод", partOfSpeech: .verb),
		Word(foreign: "עומד", native: ["стоит"], transcription: "омэ!д/омэ!дэт\nомди!м/омдо!т", partOfSpeech: .verb),
		Word(foreign: "עצוב", native: ["грустный", "печальный"], transcription: "ацу!в/ацува!", partOfSpeech: .adjective),
		Word(foreign: "שמח", native: ["счастливый", "радостный", "веселый", "весёлый"], transcription: "самэ!ах/смеха!", partOfSpeech: .adjective),
		Word(foreign: "חכם", native: ["умный", "мудрый"], transcription: "хаха!м/хахама!", partOfSpeech: .adjective),
		Word(foreign: "כל-כך", native: ["настолько"], transcription: "коль-ка!х", partOfSpeech: .other),

        // MARK: - lesson 12.1
        
        Word(foreign: "להתחתן", native: ["жениться"], transcription: "леhитхатэн", partOfSpeech: .verb),
        Word(foreign: "מתחתן", native: ["женится"], transcription: "митхатэн", partOfSpeech: .verb, nToFRemark: "м.р"),
        Word(foreign: "מתחתנת", native: ["женится"], transcription: "митхатэ!нэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
        Word(foreign: "להתלבש", native: ["одеваться"], transcription: "леhитлабэщ", partOfSpeech: .verb),
        Word(foreign: "מתלבש", native: ["одевается"], transcription: "митлабэщ", partOfSpeech: .verb, nToFRemark: "м.р"),
        Word(foreign: "מתלבשת", native: ["одевается"], transcription: "митлабэ!щэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
        Word(foreign: "להתכתב", native: ["переписываться"], transcription: "леhиткатэв", partOfSpeech: .verb),
        Word(foreign: "מתכתב", native: ["переписывается"], transcription: "миткатэв", partOfSpeech: .verb, nToFRemark: "м.р"),
        Word(foreign: "מתכתבת", native: ["переписывается"], transcription: "миткатэ!вэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
        Word(foreign: "להתרגש", native: ["волноваться", "переживать"], transcription: "леhитрагещ", partOfSpeech: .verb),
        Word(foreign: "מתרגש", native: ["волнуется"], transcription: "митрагэщ", partOfSpeech: .verb, nToFRemark: "м.р"),
        Word(foreign: "מתרגשת", native: ["волнуется"], transcription: "митрагэщэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
        Word(foreign: "להתרחץ", native: ["мыться","купаться","умываться"], transcription: "леhитрахэц", partOfSpeech: .verb),
        Word(foreign: "מתרחץ", native: ["моется","купается","умывается"], transcription: "митрахэц", partOfSpeech: .verb, nToFRemark: "м.р"),
        Word(foreign: "מתרחצת", native: ["моется","купается","умывается"], transcription: "митрахэ!цэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
        Word(foreign: "להתפלל", native: ["молиться"], transcription: "леhитпалель", partOfSpeech: .verb),
        Word(foreign: "מתפלל", native: ["молится"], transcription: "митпалель", partOfSpeech: .verb, nToFRemark: "м.р"),
        Word(foreign: "מתפללת", native: ["молится"], transcription: "митпале!лет", partOfSpeech: .verb, nToFRemark: "ж.р"),

        Word(foreign: "קרוב", native: ["близкий", "родственный", "родной"], transcription: "каров", partOfSpeech: .adjective),
        Word(foreign: "קרובה", native: ["близкая", "родственная", "родная"], transcription: "крова!", partOfSpeech: .adjective),
        Word(foreign: "בטוח", native: ["надежный", "уверенный"], transcription: "бату!ах", partOfSpeech: .adjective),
        Word(foreign: "בטוחה", native: ["надежная", "уверенная"], transcription: "б-туха!", partOfSpeech: .adjective),
        Word(foreign: "צודק", native: ["справедливый", "правый"], transcription: "цодэ!к", partOfSpeech: .adjective, nToFRemark: "прилагательное"),
        Word(foreign: "צודקת", native: ["справедливая", "правая"], transcription: "цодэ!кэт", partOfSpeech: .adjective, nToFRemark: "прилагательное"),
        Word(foreign: "אינטליגנטי", native: ["интеллигентный"], transcription: "интелиге!нти", partOfSpeech: .adjective),
        Word(foreign: "אינטליגנטית", native: ["интеллигентная"], transcription: "интелиге!нтит", partOfSpeech: .adjective),
        Word(foreign: "דתי", native: ["религиозный"], transcription: "дати!", partOfSpeech: .adjective),
        Word(foreign: "דתית", native: ["религиозная"], transcription: "дати!т", partOfSpeech: .adjective),

        Word(foreign: "חתונה", native: ["свадьба"], transcription: "хатуна/хатунот"),
        Word(foreign: "חתן", native: ["жених"], transcription: "хатан/хатаним"),
        Word(foreign: "כלה", native: ["невеста"], transcription: "кальа/кальот"),
        Word(foreign: "גיל", native: ["возраст"], transcription: "гиль"),
        Word(foreign: "פעם", native: ["раз"], transcription: "пам/пеамим"),

        Word(foreign: "תפילה", native: ["молитва"], transcription: "тфильа/тфильот"),
        Word(foreign: "בקשה", native: ["просьба", "в просьбу"], transcription: "бакаща/бакащот"),

        // MARK: - numbers (lesson 3.1 - male, lesson ז - female)
        Word(foreign: "אחת", native: ["один"], transcription: "ахат(ж.р)/эхад(м.р)", partOfSpeech: .other),
        Word(foreign: "שתיים", native: ["два"], transcription: "штайм(ж.р)/шнайм(м.р)(для счета)\nштэй(ж.р.)/шней(м.р)(для сущ.х)", partOfSpeech: .other),
        Word(foreign: "שלוש", native: ["три"], transcription: "шальош(ж.р)/шльоша(м.р)", partOfSpeech: .other),
        Word(foreign: "ארבע", native: ["четыре"], transcription: "арба(ж.р)/арба-а(м.р)", partOfSpeech: .other),
        Word(foreign: "חמש", native: ["пять"], transcription: "хамэш(ж.р)/хамиша(м.р)", partOfSpeech: .other),
        Word(foreign: "שש", native: ["шесть"], transcription: "шеш(ж.р)/шиша(м.р)", partOfSpeech: .other),
        Word(foreign: "שבע", native: ["семь"], transcription: "шева(ж.р)/шив-а(м.р)", partOfSpeech: .other),
        Word(foreign: "שמונה", native: ["восемь"], transcription: "шмонэ!(ж.р)/шмона(м.р)", partOfSpeech: .other),
        Word(foreign: "תשע", native: ["девять"], transcription: "тэ!ша(ж.р)/тиша!(м.р)", partOfSpeech: .other),
        Word(foreign: "עשר", native: ["десять"], transcription: "эсэр(ж.р)/асара(м.р)\nдля дестяков: эсрэ!(м.р)/асар(ж.р)", partOfSpeech: .other),
        Word(foreign: "עשרים", native: ["двадцать"], transcription: "эсрим", partOfSpeech: .other),
	]
}
//Word(foreign: "", native: [""], transcription: "", partOfSpeech: .verb, fToNRemark: "", nToFRemark: ""),
//Word(foreign: "", native: [""], transcription: "", partOfSpeech: .verb, fToNRemark: "", nToFRemark: ""),
