//
//  DefaultWordsList.swift
//  WordsLearning
//
//  Created by Roman Kuzin on 15.08.2022.
//

struct DefaultWordsList {
	
	static let wordsList = [
		Word(foreign: "כותב", native: ["пишет(м.р)"], transcription: "котэ!в", partOfSpeech: .verb),
		Word(foreign: "כותבת", native: ["пишет(ж.р)"], transcription: "котэ!вэт", partOfSpeech: .verb),
		Word(foreign: "לכתוב", native: ["писать"], transcription: "лихтов", partOfSpeech: .verb),
		Word(foreign: "יודע", native: ["знает", "умеет(что-то)(м.р)"], transcription: "ёде!а", partOfSpeech: .verb),
		Word(foreign: "יודעת", native: ["знает", "умеет(что-то)(ж.р)"], transcription: "ёдаат", partOfSpeech: .verb),
		Word(foreign: "לדעת", native: ["знать", "уметь"], transcription: "ладаат", partOfSpeech: .verb),
		Word(foreign: "רוצא", native: ["хочет(м.р)"], transcription: "роцэ!", partOfSpeech: .verb),
		Word(foreign: "אוהב", native: ["любит(м.р)"], transcription: "охэв", partOfSpeech: .verb),
		Word(foreign: "אוהבת", native: ["любит(ж.р)"], transcription: "охэвэт", partOfSpeech: .verb),
		Word(foreign: "לאהוב", native: ["любить"], transcription: "леэхов", partOfSpeech: .verb),

		Word(foreign: "הולך", native: ["идет", "ходит(м.р)"], transcription: "оле!х", partOfSpeech: .verb),
		Word(foreign: "הולכת", native: ["идет", "ходит(ж.р)"], transcription: "олехэт", partOfSpeech: .verb),
		Word(foreign: "להלך", native: ["идти", "ходить"], transcription: "лехалех", partOfSpeech: .verb),

		Word(foreign: "בא", native: ["приходит", "входит(м.р)"], transcription: "ба", partOfSpeech: .verb),
		Word(foreign: "נוסע", native: ["едет", "ездит(м.р)"], transcription: "носэ!а", partOfSpeech: .verb),
		Word(foreign: "נוסעת", native: ["едет", "ездит(ж.р)"], transcription: "носаат", partOfSpeech: .verb),
		Word(foreign: "לנסוע", native: ["ехать", "ездить"], transcription: "линсоа", partOfSpeech: .verb),

		Word(foreign: "מדבר", native: ["говорит(м.р)"], transcription: "медабэр", partOfSpeech: .verb),
		Word(foreign: "מדברת", native: ["говорит(ж.р)"], transcription: "медабэрэт", partOfSpeech: .verb),
		Word(foreign: "קורא", native: ["читает(м.р)"], transcription: "корэ!", partOfSpeech: .verb),
		Word(foreign: "קוראת", native: ["читает(ж.р)"], transcription: "корэт", partOfSpeech: .verb),
		Word(foreign: "לקרוא", native: ["читать"], transcription: "ликро", partOfSpeech: .verb),

		Word(foreign: "לומד", native: ["изучает", "учится(м.р)"], transcription: "льомэ!д", partOfSpeech: .verb),
		Word(foreign: "שומע", native: ["слушает", "слышет(м.р)"], transcription: "шомеа", partOfSpeech: .verb),
		Word(foreign: "שומעת", native: ["слушает", "слышет(ж.р)"], transcription: "шомаат", partOfSpeech: .verb),
		Word(foreign: "לשמוע", native: ["слушать", "слышать"], transcription: "лишмоа", partOfSpeech: .verb),

		Word(foreign: "שר", native: ["поет(м.р)"], transcription: "шир", partOfSpeech: .verb),
		Word(foreign: "שרה", native: ["поет(ж.р)"], transcription: "шира", partOfSpeech: .verb),
		Word(foreign: "לשיר", native: ["петь"], transcription: "лашир", partOfSpeech: .verb),


		Word(foreign: "עושה", native: ["делает(м.р)"], transcription: "осэ!", partOfSpeech: .verb),
		Word(foreign: "עושה", native: ["делает(ж.р)"], transcription: "оса", partOfSpeech: .verb),
		Word(foreign: "לעשות", native: ["делать"], transcription: "лаасот", partOfSpeech: .verb),


		Word(foreign: "שותה", native: ["пьет(м.р)"], transcription: "шотэ!", partOfSpeech: .verb),
		Word(foreign: "שותה", native: ["пьет(ж.р)"], transcription: "шота", partOfSpeech: .verb),
		Word(foreign: "לשתות", native: ["пить"], transcription: "лиштот", partOfSpeech: .verb),


		Word(foreign: "גר", native: ["проживает(м.р)"], transcription: "гар", partOfSpeech: .verb),
		Word(foreign: "גרה", native: ["проживает(ж.р)"], transcription: "гара!", partOfSpeech: .verb),
		Word(foreign: "לגור", native: ["проживать(где-то)"], transcription: "лагур", partOfSpeech: .verb),


		Word(foreign: "עובד", native: ["работает(м.р)"], transcription: "овэ!д", partOfSpeech: .verb),
		Word(foreign: "עובדת", native: ["работает(ж.р)"], transcription: "овэдэт", partOfSpeech: .verb),
		Word(foreign: "לעבוד", native: ["работать"], transcription: "ляавод", partOfSpeech: .verb),

			//Some other
//			Word(foreign: "אומר", native: ["сказать"], transcription: "омэ!р", partOfSpeech: .verb),
//			Word(foreign: "מבין", native: ["понимать"], transcription: "мэви!н", partOfSpeech: .verb),
//			Word(foreign: "מצטער", native: ["сожалеть"], transcription: "мицтаэ!р", partOfSpeech: .verb)
//			Word(foreign: "סרט", native: ["фильм"], transcription: "сэ!рэт", partOfSpeech: .noun),
//			Word(foreign: "ספרייה", native: ["библиотека"], transcription: "сифрия!", partOfSpeech: .noun),
//			Word(foreign: "אולי", native: ["м.б."], transcription: "уляй", partOfSpeech: .other),
//			Word(foreign: "נכון", native: ["верно"], transcription: "нахо!н", partOfSpeech: .other),
//			Word(foreign: "חנות", native: ["магазин"], transcription: "хану!т", partOfSpeech: .noun),
//			Word(foreign: "חבר", native: ["друг", "бойфренд"], transcription: "хавэ!р", partOfSpeech: .noun),
//			Word(foreign: "חברה", native: ["подруга", "герлфренд"], transcription: "хавера!", partOfSpeech: .noun),
//			Word(foreign: "מספר", native: ["номер"], transcription: "миспа!р", partOfSpeech: .noun),
//			Word(foreign: "טלפון נייד", native: ["мобильный телефон"], transcription: "тэлефон ная!д", partOfSpeech: .noun),
//			// урок 2.1
			Word(foreign: "גדול", native: ["большой(м.р)"], transcription: "гадо!ль", partOfSpeech: .adjective),
			Word(foreign: "גדולה", native: ["большая"], transcription: "гдольа!", partOfSpeech: .adjective),
			Word(foreign: "קטן", native: ["маленький(м.р)"], transcription: "ката!н", partOfSpeech: .adjective),
			Word(foreign: "קטנה", native: ["маленькая"], transcription: "ктана!", partOfSpeech: .adjective),
			Word(foreign: "חדש", native: ["новый(м.р)"], transcription: "хада!ш", partOfSpeech: .adjective),
			Word(foreign: "חדשה", native: ["новая"], transcription: "хадаша!", partOfSpeech: .adjective),
//			Word(foreign: "עתיק", native: ["древний(м.р)"], transcription: "ати!к", partOfSpeech: .adjective),
//			Word(foreign: "עתיקה", native: ["древняя"], transcription: "атика!", partOfSpeech: .adjective),
//			Word(foreign: "מודרני", native: ["современный(м.р)"], transcription: "модэ!рни", partOfSpeech: .adjective),
//			Word(foreign: "מודרנית", native: ["современная"], transcription: "модэ!рнит", partOfSpeech: .adjective),
			Word(foreign: "מיוחד", native: ["особенный(м.р)"], transcription: "мэюха!д", partOfSpeech: .adjective),
			Word(foreign: "מיוחדת", native: ["особенная"], transcription: "мэюхэ!дет", partOfSpeech: .adjective),
			Word(foreign: "יפה", native: ["красивый([ёфэ!])", "красивая([ёфа!])"], transcription: "ёфэ!/ёфа!", partOfSpeech: .adjective),
//			Word(foreign: "רומי", native: ["римский(м.р)"], transcription: "ро!ми", partOfSpeech: .adjective),
//			Word(foreign: "רומית", native: ["римская"], transcription: "ро!мит", partOfSpeech: .adjective),
//
			Word(foreign: "רחוב", native: ["улица"], transcription: "рэхо!в", partOfSpeech: .noun),
			Word(foreign: "רחובות", native: ["улицы"], transcription: "рэхово!т", partOfSpeech: .noun),
//			Word(foreign: "ארמון", native: ["замок", "дворец"], transcription: "армо!н", partOfSpeech: .noun),
//			Word(foreign: "ארמונות", native: ["замки", "дворцы"], transcription: "армоно!т", partOfSpeech: .noun),
//			Word(foreign: "ציור", native: ["рисунок"], transcription: "циу!р", partOfSpeech: .noun),
//			Word(foreign: "ציורים", native: ["рисунки"], transcription: "циури!м", partOfSpeech: .noun),
//			Word(foreign: "קיסר", native: ["император", "цезарь"], transcription: "кейса!р", partOfSpeech: .noun),
//			Word(foreign: "עלשם", native: ["имени", "памяти"], transcription: "альше!м", partOfSpeech: .other),
//			Word(foreign: "לפעמים", native: ["иногда"], transcription: "лифами!м", partOfSpeech: .other),
//			Word(foreign: "כמו", native: ["как(предлог"], transcription: "кмо!", partOfSpeech: .pretext),
//			Word(foreign: "איזה", native: ["какой(?)"], transcription: "эйзэ!", partOfSpeech: .questionWord),
//			Word(foreign: "איזו", native: ["какая(?)"], transcription: "эзо!", partOfSpeech: .questionWord),
//			Word(foreign: "אילו", native: ["какие(?)"], transcription: "э!льо", partOfSpeech: .questionWord),
//			// урок 2.2
//			Word(foreign: "דירה", native: ["квартира"], transcription: "дира!", partOfSpeech: .noun),
//			Word(foreign: "דירות", native: ["квартиры"], transcription: "диро!т", partOfSpeech: .noun),
//			Word(foreign: "חדר", native: ["комната"], transcription: "хэ!дэр", partOfSpeech: .noun),
//			Word(foreign: "חדרימ", native: ["комнаты"], transcription: "хадари!м", partOfSpeech: .noun),
//			Word(foreign: "סלון", native: ["салон(зал)"], transcription: "сальо!н", partOfSpeech: .noun),
//			Word(foreign: "סלונים", native: ["салоны(залы)"], transcription: "сальони!м", partOfSpeech: .noun),
//			Word(foreign: "מטבח", native: ["кухня"], transcription: "митба!х", partOfSpeech: .noun),
//			Word(foreign: "מטבחים", native: ["кухни"], transcription: "митбахи!м", partOfSpeech: .noun),
//			Word(foreign: "מקלחת", native: ["душ"], transcription: "микля!хат", partOfSpeech: .noun),
//			Word(foreign: "מקלחות", native: ["души(комнаты для душа)"], transcription: "микляхо!т", partOfSpeech: .noun),
//			Word(foreign: "גינה", native: ["палисадник"], transcription: "гина!", partOfSpeech: .noun),
//			Word(foreign: "גינות", native: ["палисадники"], transcription: "гино!т", partOfSpeech: .noun),
//			Word(foreign: "עצ", native: ["дерево"], transcription: "эц", partOfSpeech: .noun),
//			Word(foreign: "עצים", native: ["деревья"], transcription: "эци!м", partOfSpeech: .noun),
//			Word(foreign: "שולחן", native: ["стол"], transcription: "шульха!н", partOfSpeech: .noun),
//			Word(foreign: "שולחנות", native: ["столы"], transcription: "шульхано!т", partOfSpeech: .noun),
//			Word(foreign: "חנוכייה", native: ["ханукия"], transcription: "ханукия!", partOfSpeech: .noun),
//			Word(foreign: "חנוכיות", native: ["ханукии"], transcription: "ханукио!т", partOfSpeech: .noun),
//
//			Word(foreign: "ישן", native: ["старый(о вещах)"], transcription: "яша!н", partOfSpeech: .adjective),
//			Word(foreign: "ישנה", native: ["старая(о вещах)"], transcription: "яшана!", partOfSpeech: .adjective),
//			Word(foreign: "קלסי", native: ["класический"], transcription: "кльа!си", partOfSpeech: .adjective),
//			Word(foreign: "קלסית", native: ["класическая"], transcription: "кльаси!т", partOfSpeech: .adjective),
//			Word(foreign: "מצוין", native: ["отличный", "отлично"], transcription: "мэцуя!н", partOfSpeech: .adjective),
//			Word(foreign: "מצוינת", native: ["отличная"], transcription: "мэцуе!нет", partOfSpeech: .adjective),
//			Word(foreign: "טוב", native: ["хороший", "хорошо"], transcription: "тов", partOfSpeech: .adjective),
//			Word(foreign: "טובה", native: ["хорошая"], transcription: "това", partOfSpeech: .adjective),
//			Word(foreign: "נחמד", native: ["милый"], transcription: "нэхма!д", partOfSpeech: .adjective),
//			Word(foreign: "נחמדה", native: ["милая"], transcription: "нэхмада!", partOfSpeech: .adjective),
//
//			Word(foreign: "בטה", native: ["конечно", "несомненно", "наверняка"], transcription: "бэ!тах", partOfSpeech: .other),
//			Word(foreign: "למשל", native: ["например"], transcription: "лемаша!ль", partOfSpeech: .other),
//			Word(foreign: "בקשר ל", native: ["в отношении(кого-то, чего-то)"], transcription: "бэкэ!шер ле", partOfSpeech: .other),
//			Word(foreign: "בית", native: ["дом"], transcription: "байт", partOfSpeech: .noun),
//			Word(foreign: "בתים", native: ["дома(мн.ч)"], transcription: "бати!м", partOfSpeech: .noun),
//			Word(foreign: "כמה", native: ["несколько"], transcription: "кама!", partOfSpeech: .other),
			// урок 3.1
			// урок 3.2
//			Word(foreign: "רחיט", native: ["мебель(ед.ч, предмет)"], transcription: "рахи!т", partOfSpeech: .noun),
//			Word(foreign: "רחיטים", native: ["мебель(мн.ч, предметы)"], transcription: "рахити!м", partOfSpeech: .noun),
//			Word(foreign: "כיסא", native: ["стул"], transcription: "кисэ!", partOfSpeech: .noun),
//			Word(foreign: "כיסאות", native: ["стулья"], transcription: "кисо!т", partOfSpeech: .noun),
//			Word(foreign: "מיטה", native: ["кровать"], transcription: "мита!", partOfSpeech: .noun),
//			Word(foreign: "מיטות", native: ["кровати"], transcription: "мито!т", partOfSpeech: .noun),
//			Word(foreign: "שטיח", native: ["ковер"], transcription: "шати!ах", partOfSpeech: .noun),
//			Word(foreign: "שטיחים", native: ["ковры"], transcription: "штихи!м", partOfSpeech: .noun),
//			Word(foreign: "אוחל", native: ["палатка", "шатер"], transcription: "о!хэль", partOfSpeech: .noun),
//			Word(foreign: "אוחלים", native: ["палатки", "шатры"], transcription: "охали!м", partOfSpeech: .noun),
//			Word(foreign: "מקום", native: ["место"], transcription: "мако!м", partOfSpeech: .noun),
//			Word(foreign: "מקומות", native: ["места"], transcription: "мэкомо!т", partOfSpeech: .noun),
//			Word(foreign: "גבר", native: ["мужчина", "мужик"], transcription: "гэ!вер", partOfSpeech: .noun),
//			Word(foreign: "גברים", native: ["мужчины", "мужики"], transcription: "гвари!м", partOfSpeech: .noun),
//			Word(foreign: "בית כנסת", native: ["синагога"], transcription: "бэ!йт кне!сет", partOfSpeech: .noun),
//			Word(foreign: "בתי בנסת", native: ["синагоги"], transcription: "батэ!й кне!сет", partOfSpeech: .noun),
//			Word(foreign: "דקה", native: ["минута"], transcription: "дака!", partOfSpeech: .noun),
//			Word(foreign: "דקות", native: ["минуты"], transcription: "дако!т", partOfSpeech: .noun),
//			Word(foreign: "ישראלי", native: ["израильский" ,"израильтянин"], transcription: "исрэили!", partOfSpeech: .noun),
//			Word(foreign: "ישראלים", native: ["израильская" ,"израильтянка"], transcription: "исрэили!м", partOfSpeech: .noun),
//			Word(foreign: "בדואי", native: ["бедуинский", "бедуин"], transcription: "бэ!дуи", partOfSpeech: .noun),
//			Word(foreign: "בדואים", native: ["бедуинская", "бедуинка"], transcription: "бэдуи!м", partOfSpeech: .noun),
		Word(foreign: "חיום", native: ["сегодня(м.р)"], transcription: "хайом", partOfSpeech: .noun),
		Word(foreign: "אחר", native: ["другой"], transcription: "ахэ!р", partOfSpeech: .adjective),
		Word(foreign: "אחרת", native: ["другая"], transcription: "ахэ!рэт", partOfSpeech: .adjective),
//			Word(foreign: "אוכל", native: ["есть(м.р)", "кушать(м.р)"], transcription: "охэ!ль", partOfSpeech: .verb),
//			Word(foreign: "אוכלת", native: ["есть(ж.р)", "кушать(ж.р)"], transcription: "охэ!лэт", partOfSpeech: .verb),
		Word(foreign: "יושב", native: ["сидит(м.р)"], transcription: "йоше!в", partOfSpeech: .verb),
		Word(foreign: "יושבת", native: ["сидит(ж.р)"], transcription: "йоше!вэт", partOfSpeech: .verb),
		Word(foreign: "מטייל", native: ["гуляет(м.р)"], transcription: "метайе!ль", partOfSpeech: .verb),
		Word(foreign: "מטיילת", native: ["гуляет(ж.р)"], transcription: "метайе!льэт", partOfSpeech: .verb),
		Word(foreign: "רואה", native: ["видит(м.р|ж.р)"], transcription: "ро-э! | ро-а!", partOfSpeech: .verb),
		Word(foreign: "לראות", native: ["видеть"], transcription: "лирот", partOfSpeech: .verb),

		// lesson 5.1
		Word(foreign: "בגד", native: ["одежда"], transcription: "бэ!гед", partOfSpeech: .noun),
		Word(foreign: "בגדים", native: ["одежды"], transcription: "бгади!м", partOfSpeech: .noun),
//		Word(foreign: "ג׳ינס", native: ["джинсы(ед.ч)"], transcription: "джи!нс", partOfSpeech: .noun),
//		Word(foreign: "ג׳ינסים", native: ["джинсы(мн.ч)"], transcription: "джи!нсим", partOfSpeech: .noun),
		Word(foreign: "זמן", native: ["время(ед.ч)"], transcription: "зман", partOfSpeech: .noun),
		Word(foreign: "זמנים", native: ["время(мн.ч)","времена"], transcription: "зманим", partOfSpeech: .noun),
		Word(foreign: "מחר", native: ["завтра"], transcription: "маха!р", partOfSpeech: .noun),

		Word(foreign: "רץ", native: ["бежит(м.р.)"], transcription: "рац", partOfSpeech: .verb),
		Word(foreign: "רצה", native: ["бежит(ж.р.)"], transcription: "раца!", partOfSpeech: .verb),
		Word(foreign: "לרוץ", native: ["бегать", "бежать"], transcription: "ларуц", partOfSpeech: .verb),

//		Word(foreign: "לובש", native: ["надевать(м.р.)"], transcription: "льовэ!ш", partOfSpeech: .verb),
//		Word(foreign: "לובשת", native: ["надевать(ж.р.)"], transcription: "льовэ!шет", partOfSpeech: .verb),
//		Word(foreign: "שואל", native: ["спрашивать(м.р.)"], transcription: "що-эль", partOfSpeech: .verb),
//		Word(foreign: "שואלת", native: ["спрашивать(ж.р.)"], transcription: "що-элет", partOfSpeech: .verb),
		Word(foreign: "חושב", native: ["думает(м.р.)"], transcription: "хощев", partOfSpeech: .verb),
		Word(foreign: "חושבת", native: ["думает(ж.р.)"], transcription: "хощэвэт", partOfSpeech: .verb),
		Word(foreign: "לחשוב", native: ["думать"], transcription: "лахшов/лахашов", partOfSpeech: .verb),
		// lesson 5.2
//		Word(foreign: "", native: ["муж"], transcription: "баа!ль", partOfSpeech: .noun),
//		Word(foreign: "", native: ["мужи"], transcription: "беали!м", partOfSpeech: .noun),
//		Word(foreign: "", native: ["еврей"], transcription: "ехуди!", partOfSpeech: .noun),
//		Word(foreign: "", native: ["евреи(мужчины)"], transcription: "ехуди!м", partOfSpeech: .noun),
//		Word(foreign: "", native: ["еврейка"], transcription: "ехудия", partOfSpeech: .noun),
//		Word(foreign: "", native: ["еврейки(женщины)"], transcription: "ехудиот", partOfSpeech: .noun),
//		Word(foreign: "", native: ["равин"], transcription: "рав", partOfSpeech: .noun),
//		Word(foreign: "", native: ["равины"], transcription: "рабани!м", partOfSpeech: .noun),
//		Word(foreign: "", native: ["вопрос"], transcription: "щеэла", partOfSpeech: .noun),
//		Word(foreign: "", native: ["вопросы"], transcription: "щеэльот", partOfSpeech: .noun),
//		Word(foreign: "", native: ["имя"], transcription: "щем", partOfSpeech: .noun),
//		Word(foreign: "", native: ["имена"], transcription: "щемо!т", partOfSpeech: .noun),
//		Word(foreign: "", native: ["моё имя"], transcription: "щми", partOfSpeech: .noun),
//		Word(foreign: "", native: ["сто", "сотня", "век"], transcription: "мэ-а", partOfSpeech: .noun),
//		Word(foreign: "", native: ["сотни", "века"], transcription: "мэ-от", partOfSpeech: .noun),
//		Word(foreign: "", native: ["кто-нибудь", "кто нибудь"], transcription: "мищэху!", partOfSpeech: .other),
//		Word(foreign: "", native: ["тихо", "в тишине"], transcription: "бешэкет", partOfSpeech: .adjective),
//		Word(foreign: "", native: ["тот, кто", "тот кто"], transcription: "ми шэ", partOfSpeech: .other),
//		Word(foreign: "", native: ["как тебя зовут(? к мужчине)", "как зовут(?)"], transcription: "ма шимха", partOfSpeech: .other),
//		Word(foreign: "", native: ["как тебя зовут(? к женщине)", "как зовут(?)"], transcription: "ма шмех", partOfSpeech: .other),
//		Word(foreign: "", native: ["медленно"], transcription: "леат", partOfSpeech: .adjective),
//		Word(foreign: "", native: ["быстро"], transcription: "махэ!р", partOfSpeech: .adjective),
//		Word(foreign: "", native: ["тяжело"], transcription: "кашэ!", partOfSpeech: .adjective),
	]
}
