//
//  DefaultWordsList.swift
//  WordsLearning
//
//  Created by Roman Kuzin on 15.08.2022.
//

struct DefaultWordsList {
	
	static let wordsList = [
		Word(foreign: "כותב", native: ["пишет(м.р)"], transcription: "котэ!в", partOfSpeech: .verb),
		Word(foreign: "כותבת", native: ["пишет(ж.р)"], transcription: "котэ!вэт", partOfSpeech: .verb),
		Word(foreign: "לכתוב", native: ["писать"], transcription: "лихтов", partOfSpeech: .verb),
		Word(foreign: "יודע", native: ["знает", "умеет"], transcription: "ёде!а", partOfSpeech: .verb, nToFRemark: "что-то, м.р"),
		Word(foreign: "יודעת", native: ["знает", "умеет"], transcription: "ёдаат", partOfSpeech: .verb, nToFRemark: "что-то, ж.р"),
		Word(foreign: "לדעת", native: ["знать", "уметь"], transcription: "ладаат", partOfSpeech: .verb),
		Word(foreign: "רוצא", native: ["хочет"], transcription: "роцэ!", partOfSpeech: .verb, nToFRemark: "м.р"),

		Word(foreign: "אוהב", native: ["любит"], transcription: "оhэв", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "אוהבת", native: ["любит"], transcription: "оhэвэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "לאהוב", native: ["любить"], transcription: "леэhов", partOfSpeech: .verb),

		Word(foreign: "הולך", native: ["идет", "ходит"], transcription: "hоле!х", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "הולכת", native: ["идет", "ходит"], transcription: "hолехэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "ללכת", native: ["идти", "ходить"], transcription: "льалехэт", partOfSpeech: .verb),

		Word(foreign: "בא", native: ["приходит", "входит"], transcription: "ба", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "נוסע", native: ["едет", "ездит"], transcription: "носэ!а", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "נוסעת", native: ["едет", "ездит"], transcription: "носаат", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "לנסוע", native: ["ехать", "ездить"], transcription: "линсоа", partOfSpeech: .verb),

		Word(foreign: "מדבר", native: ["говорит"], transcription: "медабэр", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "מדברת", native: ["говорит"], transcription: "медабэрэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "קורא", native: ["читает"], transcription: "корэ!", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "קוראת", native: ["читает(ж.р)"], transcription: "корэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "לקרוא", native: ["читать"], transcription: "ликро", partOfSpeech: .verb),

		Word(foreign: "לומד", native: ["изучает", "учится"], transcription: "льомэ!д", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "שומע", native: ["слушает", "слышет"], transcription: "шомеа", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "שומעת", native: ["слушает", "слышет"], transcription: "шомаат", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "לשמוע", native: ["слушать", "слышать"], transcription: "лишмоа", partOfSpeech: .verb),

		Word(foreign: "שר", native: ["поет"], transcription: "шир", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "שרה", native: ["поет"], transcription: "шира", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "לשיר", native: ["петь"], transcription: "лашир", partOfSpeech: .verb),

		Word(foreign: "עושה", native: ["делает"], transcription: "осэ!/оса", partOfSpeech: .verb),
		Word(foreign: "לעשות", native: ["делать"], transcription: "лаасот", partOfSpeech: .verb),

		Word(foreign: "שותה", native: ["пьет"], transcription: "шотэ!|шота", partOfSpeech: .verb),
		Word(foreign: "לשתות", native: ["пить"], transcription: "лиштот", partOfSpeech: .verb),

		Word(foreign: "גר", native: ["проживает"], transcription: "гар", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "גרה", native: ["проживает"], transcription: "гара!", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "לגור", native: ["проживать"], transcription: "лагур", partOfSpeech: .verb, nToFRemark: "где-то"),

		Word(foreign: "עובד", native: ["работает"], transcription: "овэ!д", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "עובדת", native: ["работает(ж.р)"], transcription: "овэдэт", partOfSpeech: .verb, nToFRemark: ""),
		Word(foreign: "לעבוד", native: ["работать"], transcription: "ляавод", partOfSpeech: .verb),

		//Some other
//		Word(foreign: "מבין", native: ["понимает"], transcription: "мэви!н", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "אומר", native: ["рассказывает"], transcription: "омэр/омэрэт", nToFRemark: "говорит"),
		Word(foreign: "לומר", native: ["рассказывать"], transcription: "льомар", nToFRemark: "говорить"),

		Word(foreign: "מצטער", native: ["сожалеет"], transcription: "мицтаэ!р", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "מצטערת", native: ["сожалеет"], transcription: "мицтаэрэт", partOfSpeech: .verb, nToFRemark: "ж.р"),

		Word(foreign: "סרט", native: ["фильм"], transcription: "сэ!рэт", partOfSpeech: .noun),
//		Word(foreign: "ספרייה", native: ["библиотека"], transcription: "сифрия!", partOfSpeech: .noun),
		Word(foreign: "אולי", native: ["может быть"], transcription: "уляй", partOfSpeech: .other),
		Word(foreign: "נכון", native: ["верно"], transcription: "нахо!н", partOfSpeech: .other),
		Word(foreign: "חנות", native: ["магазин"], transcription: "хану!т", partOfSpeech: .noun),
		Word(foreign: "חבר", native: ["друг", "бойфренд"], transcription: "хавэ!р", partOfSpeech: .noun),
		Word(foreign: "חברה", native: ["подруга", "герлфренд"], transcription: "хавера!", partOfSpeech: .noun),
		Word(foreign: "מספר", native: ["номер"], transcription: "миспа!р", partOfSpeech: .noun),
//		Word(foreign: "טלפון נייד", native: ["мобильный телефон"], transcription: "тэлефон ная!д", partOfSpeech: .noun),

		// урок 2.1
		Word(foreign: "גדול", native: ["большой"], transcription: "гадо!ль", partOfSpeech: .adjective),
		Word(foreign: "גדולה", native: ["большая"], transcription: "гдольа!", partOfSpeech: .adjective),
		Word(foreign: "קטן", native: ["маленький"], transcription: "ката!н", partOfSpeech: .adjective),
		Word(foreign: "קטנה", native: ["маленькая"], transcription: "ктана!", partOfSpeech: .adjective),
		Word(foreign: "חדש", native: ["новый"], transcription: "хада!ш", partOfSpeech: .adjective),
		Word(foreign: "חדשה", native: ["новая"], transcription: "хадаша!", partOfSpeech: .adjective),
//		Word(foreign: "עתיק", native: ["древний(м.р)"], transcription: "ати!к", partOfSpeech: .adjective),
//		Word(foreign: "עתיקה", native: ["древняя"], transcription: "атика!", partOfSpeech: .adjective),
//		Word(foreign: "מודרני", native: ["современный(м.р)"], transcription: "модэ!рни", partOfSpeech: .adjective),
//		Word(foreign: "מודרנית", native: ["современная"], transcription: "модэ!рнит", partOfSpeech: .adjective),
		Word(foreign: "מיוחד", native: ["особенный"], transcription: "мэюха!д", partOfSpeech: .adjective),
		Word(foreign: "מיוחדת", native: ["особенная"], transcription: "мэюхэ!дет", partOfSpeech: .adjective),
		Word(foreign: "יפה", native: ["красивый", "красивая"], transcription: "ёфэ!/ёфа!", partOfSpeech: .adjective),
//		Word(foreign: "רומי", native: ["римский(м.р)"], transcription: "ро!ми", partOfSpeech: .adjective),
//		Word(foreign: "רומית", native: ["римская"], transcription: "ро!мит", partOfSpeech: .adjective),

		Word(foreign: "רחוב", native: ["улица"], transcription: "рэхо!в", partOfSpeech: .noun),
		Word(foreign: "רחובות", native: ["улицы"], transcription: "рэхово!т", partOfSpeech: .noun),
//		Word(foreign: "ארמון", native: ["замок", "дворец"], transcription: "армо!н", partOfSpeech: .noun),
//		Word(foreign: "ארמונות", native: ["замки", "дворцы"], transcription: "армоно!т", partOfSpeech: .noun),
		Word(foreign: "ציור", native: ["рисунок"], transcription: "циу!р|циури!м", partOfSpeech: .noun),
//		Word(foreign: "קיסר", native: ["император", "цезарь"], transcription: "кейса!р", partOfSpeech: .noun),
//		Word(foreign: "עלשם", native: ["имени", "памяти"], transcription: "альше!м", partOfSpeech: .other),
		Word(foreign: "לפעמים", native: ["иногда"], transcription: "лифами!м", partOfSpeech: .other),
		Word(foreign: "כמו", native: ["как"], transcription: "кмо!", partOfSpeech: .pretext, nToFRemark: "предлог"),
		Word(foreign: "איזה", native: ["какой"], transcription: "эйзэ!", partOfSpeech: .questionWord, nToFRemark: "?"),
		Word(foreign: "איזו", native: ["какая"], transcription: "эзо!", partOfSpeech: .questionWord, nToFRemark: "?"),
		Word(foreign: "אילו", native: ["какие"], transcription: "э!льо", partOfSpeech: .questionWord, nToFRemark: "?"),
//		// урок 2.2
//		Word(foreign: "דירה", native: ["квартира"], transcription: "дира!", partOfSpeech: .noun),
//		Word(foreign: "דירות", native: ["квартиры"], transcription: "диро!т", partOfSpeech: .noun),
		Word(foreign: "חדר", native: ["комната"], transcription: "хэ!дэр/хадари!м", partOfSpeech: .noun),
//		Word(foreign: "סלון", native: ["салон(зал)"], transcription: "сальо!н/сальони!м", partOfSpeech: .noun),
		Word(foreign: "מטבח", native: ["кухня"], transcription: "митба!х/митбахим", partOfSpeech: .noun),
//		Word(foreign: "מקלחת", native: ["душ"], transcription: "микля!хат/микляхо!т", partOfSpeech: .noun),
//		Word(foreign: "גינה", native: ["палисадник"], transcription: "гина!/гино!т", partOfSpeech: .noun),
		Word(foreign: "עץ", native: ["дерево"], transcription: "эц/эци!м", partOfSpeech: .noun),
		Word(foreign: "שולחן", native: ["стол"], transcription: "шульха!н/шульхано!т", partOfSpeech: .noun),
//		Word(foreign: "חנוכייה", native: ["ханукия"], transcription: "ханукия!/ханукио!т", partOfSpeech: .noun),
		Word(foreign: "ישן", native: ["старый"], transcription: "яша!н|яшана!", partOfSpeech: .adjective, nToFRemark: "о вещах"),
//		Word(foreign: "קלסי", native: ["класический"], transcription: "кльа!си", partOfSpeech: .adjective),
//		Word(foreign: "קלסית", native: ["класическая"], transcription: "кльаси!т", partOfSpeech: .adjective),
//		Word(foreign: "מצוין", native: ["отличный", "отлично"], transcription: "мэцуя!н/мэцуе!нет", partOfSpeech: .adjective),
//		Word(foreign: "טוב", native: ["хороший", "хорошо"], transcription: "тов/това", partOfSpeech: .adjective),
		Word(foreign: "נחמד", native: ["милый", "хороший"], transcription: "нэхма!д|нэхмада!", partOfSpeech: .adjective),
		Word(foreign: "בטה", native: ["конечно", "несомненно", "наверняка"], transcription: "бэ!тах", partOfSpeech: .other),
		Word(foreign: "למשל", native: ["например"], transcription: "лемаша!ль", partOfSpeech: .other),
//		Word(foreign: "בקשר ל", native: ["в отношении(кого-то, чего-то)"], transcription: "бэкэ!шер ле", partOfSpeech: .other),
//		Word(foreign: "בית", native: ["дом"], transcription: "байт/бати!м", partOfSpeech: .noun),
//		Word(foreign: "כמה", native: ["несколько"], transcription: "кама!", partOfSpeech: .other),
		// урок 3.1

		// урок 3.2
//		Word(foreign: "רחיט", native: ["мебель(ед.ч, предмет)"], transcription: "рахи!т", partOfSpeech: .noun),
//		Word(foreign: "רחיטים", native: ["мебель(мн.ч, предметы)"], transcription: "рахити!м", partOfSpeech: .noun),
//		Word(foreign: "כיסא", native: ["стул"], transcription: "кисэ!/кисо!т", partOfSpeech: .noun),
//		Word(foreign: "מיטה", native: ["кровать"], transcription: "мита!/мито!т", partOfSpeech: .noun),
//		Word(foreign: "שטיח", native: ["ковер"], transcription: "шати!ах/штихи!м", partOfSpeech: .noun),
//		Word(foreign: "אוחל", native: ["палатка", "шатер"], transcription: "о!хэль/охали!м", partOfSpeech: .noun),
//		Word(foreign: "מקום", native: ["место"], transcription: "мако!м/мэкомо!т", partOfSpeech: .noun),
//		Word(foreign: "גבר", native: ["мужчина", "мужик"], transcription: "гэ!вер/гвари!м", partOfSpeech: .noun),
//		Word(foreign: "בית כנסת", native: ["синагога"], transcription: "бэ!йт кне!сет", partOfSpeech: .noun),
//		Word(foreign: "בתי בנסת", native: ["синагоги"], transcription: "батэ!й кне!сет", partOfSpeech: .noun),
//		Word(foreign: "דקה", native: ["минута"], transcription: "дака!/дако!т", partOfSpeech: .noun),
//		Word(foreign: "ישראלי", native: ["израильский" ,"израильтянин"], transcription: "исрэили!", partOfSpeech: .noun),
//		Word(foreign: "ישראלים", native: ["израильская" ,"израильтянка"], transcription: "исрэили!м", partOfSpeech: .noun),
//		Word(foreign: "בדואי", native: ["бедуинский", "бедуин"], transcription: "бэ!дуи", partOfSpeech: .noun),
//		Word(foreign: "בדואים", native: ["бедуинская", "бедуинка"], transcription: "бэдуи!м", partOfSpeech: .noun),
		Word(foreign: "חיום", native: ["сегодня(м.р)"], transcription: "хайом", partOfSpeech: .noun),

		Word(foreign: "אחר", native: ["другой"], transcription: "ахэ!р", partOfSpeech: .adjective),
		Word(foreign: "אחרת", native: ["другая"], transcription: "ахэ!рэт", partOfSpeech: .adjective),

		Word(foreign: "אוכל", native: ["ест", "кушает"], transcription: "охэ!ль", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "אוכלת", native: ["ест", "кушает"], transcription: "охэ!лэт", partOfSpeech: .verb, nToFRemark: "ж.р"),

//		Word(foreign: "יושב", native: ["сидит"], transcription: "йоше!в/йоше!вэт"),
//		Word(foreign: "מטייל", native: ["гуляет"], transcription: "метайе!ль/метайе!льэт"),

		Word(foreign: "רואה", native: ["видит(м.р|ж.р)"], transcription: "ро-э! | ро-а!", partOfSpeech: .verb),
		Word(foreign: "לראות", native: ["видеть"], transcription: "лирот", partOfSpeech: .verb),

		// lesson 5.1
		Word(foreign: "בגד", native: ["одежда"], transcription: "бэ!гед", partOfSpeech: .noun),
		Word(foreign: "בגדים", native: ["одежды"], transcription: "бгади!м", partOfSpeech: .noun),
//		Word(foreign: "ג׳ינס", native: ["джинсы(ед.ч)"], transcription: "джи!нс", partOfSpeech: .noun),
//		Word(foreign: "ג׳ינסים", native: ["джинсы(мн.ч)"], transcription: "джи!нсим", partOfSpeech: .noun),
		Word(foreign: "זמן", native: ["время"], transcription: "зман", partOfSpeech: .noun),
		Word(foreign: "זמנים", native: ["времена"], transcription: "зманим", partOfSpeech: .noun),
		Word(foreign: "מחר", native: ["завтра"], transcription: "маха!р", partOfSpeech: .noun),

		Word(foreign: "רץ", native: ["бежит"], transcription: "рац", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "רצה", native: ["бежит"], transcription: "раца!", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "לרוץ", native: ["бегать", "бежать"], transcription: "ларуц", partOfSpeech: .verb),

//		Word(foreign: "לובש", native: ["надевает"], transcription: "льовэ!ш/льовэ!шет"),
//		Word(foreign: "שואל", native: ["спрашивает"], transcription: "що-эль/що-элет"),

		Word(foreign: "חושב", native: ["думает"], transcription: "хощев", partOfSpeech: .verb, nToFRemark: "м.р"),
		Word(foreign: "חושבת", native: ["думает"], transcription: "хощэвэт", partOfSpeech: .verb, nToFRemark: "ж.р"),
		Word(foreign: "לחשוב", native: ["думать"], transcription: "лахшов/лахашов", partOfSpeech: .verb),

		// lesson 5.2
//		Word(foreign: "", native: ["муж"], transcription: "баа!ль", partOfSpeech: .noun),
//		Word(foreign: "", native: ["мужи"], transcription: "беали!м", partOfSpeech: .noun),
//		Word(foreign: "", native: ["еврей"], transcription: "ехуди!", partOfSpeech: .noun),
//		Word(foreign: "", native: ["евреи(мужчины)"], transcription: "ехуди!м", partOfSpeech: .noun),
//		Word(foreign: "", native: ["еврейка"], transcription: "ехудия", partOfSpeech: .noun),
//		Word(foreign: "", native: ["еврейки(женщины)"], transcription: "ехудиот", partOfSpeech: .noun),
//		Word(foreign: "", native: ["равин"], transcription: "рав", partOfSpeech: .noun),
//		Word(foreign: "", native: ["равины"], transcription: "рабани!м", partOfSpeech: .noun),
//		Word(foreign: "", native: ["имя"], transcription: "щем/щемо!т", partOfSpeech: .noun),
//		Word(foreign: "", native: ["моё имя"], transcription: "щми", partOfSpeech: .noun),
//		Word(foreign: "", native: ["кто-нибудь", "кто нибудь"], transcription: "мищэху!", partOfSpeech: .other),
//		Word(foreign: "", native: ["тот, кто", "тот кто"], transcription: "ми шэ", partOfSpeech: .other),
//		Word(foreign: "", native: ["как тебя зовут(? к мужчине)", "как зовут(?)"], transcription: "ма шимха", partOfSpeech: .other),
//		Word(foreign: "", native: ["как тебя зовут(? к женщине)", "как зовут(?)"], transcription: "ма шмех", partOfSpeech: .other),
//		Word(foreign: "", native: ["медленно"], transcription: "леат", partOfSpeech: .adjective),
//		Word(foreign: "", native: ["быстро"], transcription: "махэ!р", partOfSpeech: .adjective),
//		Word(foreign: "", native: ["тяжело"], transcription: "кашэ!", partOfSpeech: .adjective),


		// lesson 6.2
		Word(foreign: "דרך", native: ["дорога", "путь"], transcription: "дэрэх/драхим", partOfSpeech: .noun),
		Word(foreign: "מלון", native: ["отель"], transcription: "мальон/мэльонот", partOfSpeech: .noun),
		Word(foreign: "ים המלח", native: ["мертвое море"], transcription: "ям ха мэлях", partOfSpeech: .noun),
		Word(foreign: "מדבר", native: ["пустыня"], transcription: "мидбар", partOfSpeech: .noun),
		Word(foreign: "שקט", native: ["тишина"], transcription: "шекет", partOfSpeech: .noun),
		Word(foreign: "אוהל", native: ["шатер"], transcription: "оhэль/оhалим", partOfSpeech: .noun),
		Word(foreign: "הכול", native: ["все", "всё"], transcription: "хаколь", partOfSpeech: .other),
		Word(foreign: "חם", native: ["горячий"], transcription: "хам/хамим", partOfSpeech: .noun),
		Word(foreign: "עיינות", native: ["источники", "родники"], transcription: "аянот", partOfSpeech: .noun),
		Word(foreign: "תייר", native: ["турист"], transcription: "тайар/тайарим", partOfSpeech: .noun),
		Word(foreign: "מחוייל", native: ["изза границы","из-за границы"], transcription: "михуль", partOfSpeech: .other),
		Word(foreign: "ארץ", native: ["страна", "земля"], transcription: "э!рэц", partOfSpeech: .noun),
		Word(foreign: "חולה", native: ["больной", "больная"], transcription: "хольэ/хольэ", partOfSpeech: .adjective),
		Word(foreign: "אמצע", native: ["середина", "половина"], transcription: "э!мца", partOfSpeech: .other),
		Word(foreign: "הם", native: ["они", "равно"], transcription: "hэм", partOfSpeech: .other),
		Word(foreign: "ועוד", native: ["плюс"], transcription: "вэод", partOfSpeech: .other),
		Word(foreign: "פחות", native: ["минус"], transcription: "пахот", partOfSpeech: .other),

		// lesson 7.2
		Word(foreign: "בעיה", native: ["проблема"], transcription: "бэ-айа/бэ-айот(ж.р)", partOfSpeech: .noun),
		Word(foreign: "כובע", native: ["кепка", "шляпа"], transcription: "кова/коваим", partOfSpeech: .noun),
		Word(foreign: "כובע טמבל", native: ["панама", "панамка"], transcription: "кова тэ!мэль", partOfSpeech: .noun),
		Word(foreign: "צבא", native: ["армия"], transcription: "цава/цва!от", partOfSpeech: .noun),
		Word(foreign: "מלחמה", native: ["война"], transcription: "мильхама/мильхамот", partOfSpeech: .noun),
		Word(foreign: "שנה", native: ["год"], transcription: "щана!/щаним", partOfSpeech: .noun),
		Word(foreign: "סיפור", native: ["рассказ"], transcription: "сипур/сипурим", partOfSpeech: .noun),
		Word(foreign: "משוגע", native: ["сумасшедший"], transcription: "мэщуга/мэщугаат", partOfSpeech: .adjective),

		// lesson 7.2_additional
		Word(foreign: "מעניין", native: ["интересно"], transcription: "меанйен", partOfSpeech: .other),
		Word(foreign: "פוגש", native: ["встречает", "знакомится"], transcription: "погэщ/погэщэт"),
		Word(foreign: "לפגוש", native: ["встречать", "знакомиться"], transcription: "лифгош"),
		Word(foreign: "חקלאות", native: ["сельское хозяйство"], transcription: "хакляут", partOfSpeech: .verb),
		Word(foreign: "טבע", native: ["природа"], transcription: "те!ва", partOfSpeech: .verb),
		Word(foreign: "לילה", native: ["ночь", "вечер"], transcription: "льайльа", partOfSpeech: .verb),
		Word(foreign: "אבל", native: ["но"], transcription: "аваль", partOfSpeech: .verb),
		Word(foreign: "להיות", native: ["быть", "стать", "становиться"], transcription: "лехийот", partOfSpeech: .verb),
		Word(foreign: "משפחה", native: ["семья"], transcription: "мищпаха", partOfSpeech: .verb),
		Word(foreign: "שואל", native: ["спрашивает"], transcription: "шоэль/шоэ!лет"),
		Word(foreign: "לשאול", native: ["спрашивать"], transcription: "лишоль"),
		Word(foreign: "שאלה", native: ["вопрос"], transcription: "щэ-ельа/ще-ельот", partOfSpeech: .verb),

		// lesson 12.1
		Word(foreign: "להתחתן", native: ["жениться"], transcription: "леhитхатэн", partOfSpeech: .verb),
		Word(foreign: "מתחתן", native: ["женится"], transcription: "митхатэн", partOfSpeech: .verb, fToNRemark: "м.р", nToFRemark: "м.р"),
		Word(foreign: "מתחתנת", native: ["женится"], transcription: "митхатэ!нэт", partOfSpeech: .verb, fToNRemark: "ж.р", nToFRemark: "ж.р"),
		Word(foreign: "להתלבש", native: ["одеваться"], transcription: "леhитлабэщ", partOfSpeech: .verb),
		Word(foreign: "מתלבש", native: ["одевается"], transcription: "митлабэщ", partOfSpeech: .verb, fToNRemark: "м.р", nToFRemark: "м.р"),
		Word(foreign: "מתלבשת", native: ["одевается"], transcription: "митлабэ!щэт", partOfSpeech: .verb, fToNRemark: "ж.р", nToFRemark: "ж.р"),
		Word(foreign: "להתכתב", native: ["переписываться"], transcription: "леhиткатэв", partOfSpeech: .verb, fToNRemark: "", nToFRemark: ""),
		Word(foreign: "מתכתב", native: ["переписывается"], transcription: "миткатэв", partOfSpeech: .verb, fToNRemark: "м.р", nToFRemark: "м.р"),
		Word(foreign: "מתכתבת", native: ["переписывается"], transcription: "миткатэ!вэт", partOfSpeech: .verb, fToNRemark: "ж.р", nToFRemark: "ж.р"),
		Word(foreign: "להתרגש", native: ["волноваться"], transcription: "леhитрагещ", partOfSpeech: .verb),
		Word(foreign: "מתרגש", native: ["волнуется"], transcription: "митрагэщ", partOfSpeech: .verb, fToNRemark: "м.р", nToFRemark: "м.р"),
		Word(foreign: "מתרגשת", native: ["волнуется"], transcription: "митрагэщэт", partOfSpeech: .verb, fToNRemark: "ж.р", nToFRemark: "ж.р"),
		Word(foreign: "להתרחץ", native: ["мыться","купаться","умываться"], transcription: "леhитрахэц", partOfSpeech: .verb),
		Word(foreign: "מתרחץ", native: ["моется","купается","умывается"], transcription: "митрахэц", partOfSpeech: .verb, fToNRemark: "м.р", nToFRemark: "м.р"),
		Word(foreign: "מתרחצת", native: ["моется","купается","умывается"], transcription: "митрахэ!цэт", partOfSpeech: .verb, fToNRemark: "ж.р", nToFRemark: "ж.р"),
		Word(foreign: "להתפלל", native: ["молиться"], transcription: "леhитпалель", partOfSpeech: .verb),
		Word(foreign: "מתפלל", native: ["молится"], transcription: "митпалель", partOfSpeech: .verb, fToNRemark: "м.р", nToFRemark: "м.р"),
		Word(foreign: "מתפללת", native: ["молится"], transcription: "митпале!лет", partOfSpeech: .verb, fToNRemark: "ж.р", nToFRemark: "ж.р"),

		Word(foreign: "קרוב", native: ["близкий", "родственный", "родной"], transcription: "каров", partOfSpeech: .adjective),
		Word(foreign: "קרובה", native: ["близкая", "родственная", "родная"], transcription: "крова!", partOfSpeech: .adjective),
		Word(foreign: "בטוח", native: ["надежный", "уверенный"], transcription: "бату!ах", partOfSpeech: .adjective),
		Word(foreign: "בטוחה", native: ["надежная", "уверенная"], transcription: "б-туха!", partOfSpeech: .adjective),
		Word(foreign: "צודק", native: ["справедливый", "правый"], transcription: "цодэ!к", partOfSpeech: .adjective, nToFRemark: "прилагательное"),
		Word(foreign: "צודקת", native: ["справедливая", "правая"], transcription: "цодэ!кэт", partOfSpeech: .adjective, nToFRemark: "прилагательное"),
		Word(foreign: "אינטליגנטי", native: ["интеллигентный"], transcription: "интелиге!нти", partOfSpeech: .adjective),
		Word(foreign: "אינטליגנטית", native: ["интеллигентная"], transcription: "интелиге!нтит", partOfSpeech: .adjective),
		Word(foreign: "דתי", native: ["религиозный"], transcription: "дати!", partOfSpeech: .adjective),
		Word(foreign: "דתית", native: ["религиозная"], transcription: "дати!т", partOfSpeech: .adjective),

		Word(foreign: "חתונה", native: ["свадьба"], transcription: "хатуна/хатунот", partOfSpeech: .noun),
		Word(foreign: "חתן", native: ["жених"], transcription: "хатан/хатаним", partOfSpeech: .noun),
		Word(foreign: "כלה", native: ["невеста"], transcription: "кальа/кальот", partOfSpeech: .noun),
		Word(foreign: "גיל", native: ["возраст"], transcription: "гиль", partOfSpeech: .noun),
		Word(foreign: "פעם", native: ["раз"], transcription: "пам/пеамим", partOfSpeech: .noun),

		Word(foreign: "תפילה", native: ["молитва"], transcription: "тфильа/тфильот", partOfSpeech: .noun),
		Word(foreign: "בקשה", native: ["просьба", "в просьбу"], transcription: "бакаща/бакащот", partOfSpeech: .noun),

		// numbers (lesson 3.1 - male, lesson ז - female) 
		Word(foreign: "אחת", native: ["один"], transcription: "ахат(ж.р)/эхад(м.р)", partOfSpeech: .other),
		Word(foreign: "שתיים", native: ["два"], transcription: "штайм(ж.р)/шнайм(м.р)(для счета)\nштэй(ж.р.)/шней(м.р)(для сущ.х)", partOfSpeech: .other),
		Word(foreign: "שלוש", native: ["три"], transcription: "шальош(ж.р)/шльоша(м.р)", partOfSpeech: .other),
		Word(foreign: "ארבע", native: ["четыре"], transcription: "арба(ж.р)/арба-а(м.р)", partOfSpeech: .other),
		Word(foreign: "חמש", native: ["пять"], transcription: "хамэш(ж.р)/хамиша(м.р)", partOfSpeech: .other),
		Word(foreign: "שש", native: ["шесть"], transcription: "шеш(ж.р)/шиша(м.р)", partOfSpeech: .other),
		Word(foreign: "שבע", native: ["семь"], transcription: "шева(ж.р)/шив-а(м.р)", partOfSpeech: .other),
		Word(foreign: "שמונה", native: ["восемь"], transcription: "шмонэ!(ж.р)/шмона(м.р)", partOfSpeech: .other),
		Word(foreign: "תשע", native: ["девять"], transcription: "тэ!ша(ж.р)/тиша!(м.р)", partOfSpeech: .other),
		Word(foreign: "עשר", native: ["десять"], transcription: "эсэр(ж.р)/асара(м.р)\n(для дестяков - эсрэ!(м.р)/асар(ж.р))", partOfSpeech: .other),
		Word(foreign: "עשרים", native: ["двадцать"], transcription: "эсрим", partOfSpeech: .other),
		Word(foreign: "מאה", native: ["сто", "сотня", "век"], transcription: "мэ-а(м.р)/мэ-от(ж.р)", partOfSpeech: .other),
	]
}
//Word(foreign: "", native: [""], transcription: "", partOfSpeech: .verb, fToNRemark: "", nToFRemark: ""),
//Word(foreign: "", native: [""], transcription: "", partOfSpeech: .verb, fToNRemark: "", nToFRemark: ""),
